
package hff.elegant.blog.web.jws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloServiceService", targetNamespace = "http://www.webservice.com", wsdlLocation = "http://localhost:8888/loveff-service?wsdl")
public class HelloServiceService
    extends Service
{

    private final static URL HELLOSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(HelloServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = HelloServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/bumpkins-service?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/loveff-service?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOSERVICESERVICE_WSDL_LOCATION = url;
    }

    public HelloServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceService() {
        super(HELLOSERVICESERVICE_WSDL_LOCATION, new QName("http://www.webservice.com", "HelloServiceService"));
    }

    /**
     * 
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "web-service")
    public HelloService getWebService() {
        return super.getPort(new QName("http://www.webservice.com", "web-service"), HelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "web-service")
    public HelloService getWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservice.com", "web-service"), HelloService.class, features);
    }

}
