
package hff.elegant.blog.web.jws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "helloService", targetNamespace = "http://www.webservice.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "sayHello")
    @WebResult(partName = "return")
    public String sayHello(
        @WebParam(name = "name", partName = "name")
        String name);

}
